name: 'Build pull request'

on:
  pull_request:
    types: ['opened', 'synchronize', 'edited']

jobs:
  build-pull-request:
    name: 'Build pull request'
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{github.event.number}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.2
      - name: Setup node
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 17.9.0
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: preview
          path: dist
          retention-days: 1
      - name: Save pr number
        run: echo ${PR_NUMBER} > ./pr.txt
      - name: Upload pr number
        uses: actions/upload-artifact@v3.1.0
        with:
          name: pr
          path: ./pr.txt
          retention-days: 1