name: 'Build PR'

on:
  pull_request:
    types: ['opened', 'synchronize']

jobs:
    build:
        runs-on: ubuntu-latest
        env:
          PR_NUMBER: ${{github.event.number}}
        steps:
            - uses: actions/checkout@v3.0.0
            - name: Build
              run: npm ci && npm run build
            - name: Upload Artifact
              uses: actions/upload-artifact@v3.0.0
              with:
                  name: previewbuild
                  path: dist
                  retention-days: 1
            - uses: actions/github-script@v6.0.0
              with:
                script: |
                    var fs = require('fs');
                    fs.writeFileSync('${{github.workspace}}/pr.json', JSON.stringify(context.payload.pull_request));
            - name: Upload PR Info
              uses: actions/upload-artifact@v3.0.0
              with:
                  name: pr.json
                  path: pr.json
                  retention-days: 1
            - name: Build Docker image
              uses: docker/build-push-action@v2.10.0
              with:
                context: .
                push: false
