on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Build
        run: npm ci && npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2.0.0
        with:
          name: "cinny-${{ steps.get_tag.outputs.value }}.tar.gz"
          path: dist
          retention-days: 1

  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.0.0
      - name: Create Release Notes
        uses: actions/github-script@v4.0.2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.request(`POST /repos/${{ github.repository }}/releases`, {
              tag_name: "${{ github.ref }}",
              releases_upload: "cinny-${{ steps.get_tag.outputs.value }}.tar.gz",
              generate_release_notes: true
            });
