name: 'Deploy to Netlify (dev)'

on:
  push:
    branches:
       - test-tcb

jobs:
  deploy-to-netlify:
    name: 'Deploy'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.2
      - name: Build and deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@fb6a5f936a4b06a8f7793e69fc5a022ffe39807a
        with:
          install_command: "npm ci"
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE3_ID }}
          BUILD_DIRECTORY: "dist"
          NETLIFY_DEPLOY_MESSAGE: "Dev deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
