name: "Publish Tauri App"
on:
  release:
    types: [published]

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3.0.0
    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup node
      uses: actions/setup-node@v3.0.0
      with:
        node-version: 16
    - name: Install Rust stable
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
    - name: Install webkit2gtk (ubuntu only)
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y webkit2gtk-4.0
    - name: Install app dependencies and build it
      run: npm ci && npm run build
    - uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        releaseId: ${{ steps.get_release.outputs.upload_url }}
    - name: Get app version
      id: vars
      run: echo ::set-output name=tag::$(jq .package.version src-tauri/tauri.conf.json | tr -d '"')
    - name: Upload tagged release (macos)
      if: matrix.platform == 'macos-latest'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          src-tauri/target/release/bundle/dmg/cinny_${{ steps.vars.outputs.tag }}_x64.dmg
    - name: Upload tagged release (ubuntu)
      if: matrix.platform == 'ubuntu-latest'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          src-tauri/target/release/bundle/appimage/cinny_${{ steps.vars.outputs.tag }}_amd64.AppImage
          src-tauri/target/release/bundle/deb/cinny_${{ steps.vars.outputs.tag }}_amd64.deb
    - name: Upload tagged release (windows)
      if: matrix.platform == 'windows-latest'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          src-tauri\target\release\bundle\msi\cinny_${{ steps.vars.outputs.tag }}_x64_en-US.msi
          
