name: "publish"
on:
  release:
    types: [published]

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3.0.0
    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: setup node
      uses: actions/setup-node@v3.0.0
      with:
        node-version: 16
    - name: install Rust stable
      uses: actions-rs/toolchain@v1.0.7
      with:
        toolchain: stable
    - name: install webkit2gtk (ubuntu only)
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y webkit2gtk-4.0
    - name: install app dependencies and build it
      run: npm ci && npm run build
    - uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        releaseId: ${{ steps.get_release.outputs.upload_url }}
  upload-assest:
    runs-on: ubuntu-latest
    steps:
    - name: Get app version
      id: vars
      run: echo ::set-output name=tag::$(jq .package.version tauri.conf.json)
    - name: Upload tagged release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          /src-tauri/target/release/bundle/appimage/cinny_${{ steps.vars.outputs.tag }}_amd64.AppImage
          /src-tauri/target/release/bundle/deb/cinny_${{ steps.vars.outputs.tag }}_amd64.deb
          /src-tauri/target/release/bundle/dmg/cinny_${{ steps.vars.outputs.tag }}_x64.dmg
          /src-tauri/target/release/bundle/msi/cinny_${{ steps.vars.outputs.tag }}_x64_en-US.msi
          
