name: 'Deploy to Netlify (dev)'

on:
  push:
    branches:
       - test22

jobs:
  upload-assest:
    runs-on: ubuntu-latest
    steps:
    - name: Get app version
      id: vars
      run: echo ::set-output name=tag::$(jq .package.version /src-tauri/tauri.conf.json)
    - name: see
      run: ls -a
    - name: Upload tagged release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          /src-tauri/target/release/bundle/appimage/cinny_${{ steps.vars.outputs.tag }}_amd64.AppImage
          /src-tauri/target/release/bundle/deb/cinny_${{ steps.vars.outputs.tag }}_amd64.deb
          /src-tauri/target/release/bundle/dmg/cinny_${{ steps.vars.outputs.tag }}_x64.dmg
          /src-tauri/target/release/bundle/msi/cinny_${{ steps.vars.outputs.tag }}_x64_en-US.msi
