name: 'Deploy test2332'

on:
  push:
    branches:
       - tauri-app

jobs:
  upload-assest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.0
    - name: Build Docker image
      uses: docker/build-push-action@v2.9.0
      with:
        context: .
        push: false
